#![allow(dead_code, unused)]
// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
//
// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
// Any manual changes to this file will be overwritten.
pub mod rocket_pool;
mod rocket_pool_abi_gen;
