apiVersion: v1
kind: Service
metadata:
  name: {{ include "rindexer.fullname" . }}
  labels:
    {{- include "rindexer.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rindexer.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
