
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
/// Any manual changes to this file will be overwritten.
use super::networks::{get_base_provider, get_polygon_provider};
use ethers::{
    abi::Address,
    contract::abigen,
    providers::{Http, Provider, RetryClient},
};
use std::sync::Arc;

abigen!(
    InjectedGlobal,
    "/Users/joshstevens/code/rindexer/rindexer_demo/abis/lens-registry-events-abi.json"
);

pub fn get_injected_global() -> InjectedGlobal<Arc<Provider<RetryClient<Http>>>> {
    let address: Address = "0x2E645469f354BB4F5c8a05B3b30A929361cf77eC"
        .parse()
        .unwrap();

    InjectedGlobal::new(address, Arc::new(get_polygon_provider().clone()))
}
