#![allow(dead_code, unused)]

pub mod blah_baby;
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer
/// Any manual changes to this file will be overwritten.
pub mod global_contracts;
pub mod lens_registry_example;
pub mod networks;
