/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
/// Any manual changes to this file will be overwritten.
use ethers::providers::{Http, Provider, RetryClient};
use rindexer_core::lazy_static;
use rindexer_core::provider::create_retry_client;
use std::sync::Arc;

lazy_static! {
    static ref POLYGON_PROVIDER: Arc<Provider<RetryClient<Http>>> = create_retry_client(
        "https://polygon-mainnet.g.alchemy.com/v2/QLjF9OO90XrczIsf6Nud7RoSc8mLSyra"
    )
    .expect("Error creating provider");
    static ref BASE_PROVIDER: Arc<Provider<RetryClient<Http>>> = create_retry_client(
        "https://base-mainnet.g.alchemy.com/v2/fb_ZprvGkE5uIH6bK6BvfFVDSABpTPXk"
    )
    .expect("Error creating provider");
}
pub fn get_polygon_provider() -> Arc<Provider<RetryClient<Http>>> {
    POLYGON_PROVIDER.clone()
}

pub fn get_base_provider() -> Arc<Provider<RetryClient<Http>>> {
    BASE_PROVIDER.clone()
}
