/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
/// Any manual changes to this file will be overwritten.
use ethers::providers::{Http, Provider, RetryClient};
use rindexer_core::{
    lazy_static,
    provider::{create_client, JsonRpcCachedProvider},
    public_read_env_value,
};
use std::sync::Arc;

lazy_static! {
    static ref POLYGON_PROVIDER: Arc<JsonRpcCachedProvider> = create_client(
        &public_read_env_value("MAINNET_RPC").unwrap_or("MAINNET_RPC".to_string()),
        None
    )
    .expect("Error creating provider");
    static ref BASE_PROVIDER: Arc<JsonRpcCachedProvider> = create_client(
        &public_read_env_value("BASE_RPC").unwrap_or("BASE_RPC".to_string()),
        None
    )
    .expect("Error creating provider");
}
pub fn get_polygon_provider_cache() -> Arc<JsonRpcCachedProvider> {
    POLYGON_PROVIDER.clone()
}

pub fn get_polygon_provider() -> Arc<Provider<RetryClient<Http>>> {
    POLYGON_PROVIDER.get_inner_provider()
}

pub fn get_base_provider_cache() -> Arc<JsonRpcCachedProvider> {
    BASE_PROVIDER.clone()
}

pub fn get_base_provider() -> Arc<Provider<RetryClient<Http>>> {
    BASE_PROVIDER.get_inner_provider()
}

pub fn get_provider_cache_for_network(network: &str) -> Arc<JsonRpcCachedProvider> {
    if network == "polygon" {
        return get_polygon_provider_cache();
    }

    if network == "base" {
        return get_base_provider_cache();
    }
    panic!("Network not supported")
}
