pub mod build;

mod context_bindings;
mod database_bindings;
mod docker;
mod events_bindings;
mod networks_bindings;
mod trace_bindings;

pub use docker::generate_docker_file;

/// Header for generated files. Emitted once at the top of each generated `.rs` file.
pub(crate) const GENERATED_FILE_HEADER: &str = "\
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
/// Any manual changes to this file will be overwritten.";

/// Standard `#![allow]` attributes for generated binding files.
pub(crate) const GENERATED_ALLOW_ATTRS: &str = "#![allow(non_camel_case_types, clippy::enum_variant_names, clippy::too_many_arguments, clippy::upper_case_acronyms, clippy::type_complexity, dead_code)]";
