[package]
name = "rust_clickhouse"
version = "0.1.0"
edition = "2024"

[dependencies]
rindexer = { path = "../../core" }
tokio = { version = "1", features = ["full"] }
alloy = { version = "1.0.37", features = ["full"] }

[features]
reth = ["rindexer/reth"]
