#![allow(dead_code, unused)]

pub mod erc_20_filter;
mod erc_20_filter_abi_gen;
pub mod playground_types_filter;
mod playground_types_filter_abi_gen;
pub mod rocket_pool_eth;
mod rocket_pool_eth_abi_gen;
pub mod uniswap_v3_factory;
mod uniswap_v3_factory_abi_gen;
pub mod uniswap_v3_pool;
mod uniswap_v3_pool_abi_gen;
pub mod uniswap_v3_pool_filter;
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer
/// Any manual changes to this file will be overwritten.
mod uniswap_v3_pool_filter_abi_gen;
