#![allow(
    non_camel_case_types,
    clippy::enum_variant_names,
    clippy::too_many_arguments,
    clippy::upper_case_acronyms,
    clippy::type_complexity,
    dead_code
)]
use std::{
    any::Any,
    error::Error,
    future::Future,
    path::{Path, PathBuf},
    pin::Pin,
    sync::Arc,
};

use ethers::{
    abi::Address,
    providers::{Http, Provider, RetryClient},
    types::{Bytes, H256},
};
use rindexer::{
    async_trait,
    event::{
        callback_registry::{
            EventCallbackRegistry, EventCallbackRegistryInformation, EventCallbackResult,
            EventResult, TxInformation,
        },
        contract_setup::{ContractInformation, NetworkContract},
    },
    generate_random_id,
    manifest::{
        contract::{Contract, ContractDetails},
        yaml::read_manifest,
    },
    provider::JsonRpcCachedProvider,
    AsyncCsvAppender, FutureExt, PostgresClient,
};

use super::super::super::super::typings::{
    database::get_or_init_postgres_client, networks::get_provider_cache_for_network,
};
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
/// Any manual changes to this file will be overwritten.
use super::uniswap_v3_pool_filter_abi_gen::rindexer_uniswap_v3_pool_filter_gen::{
    self, RindexerUniswapV3PoolFilterGen,
};

pub type BurnData = rindexer_uniswap_v3_pool_filter_gen::BurnFilter;

#[derive(Debug, Clone)]
pub struct BurnResult {
    pub event_data: BurnData,
    pub tx_information: TxInformation,
}

pub type CollectData = rindexer_uniswap_v3_pool_filter_gen::CollectFilter;

#[derive(Debug, Clone)]
pub struct CollectResult {
    pub event_data: CollectData,
    pub tx_information: TxInformation,
}

pub type CollectProtocolData = rindexer_uniswap_v3_pool_filter_gen::CollectProtocolFilter;

#[derive(Debug, Clone)]
pub struct CollectProtocolResult {
    pub event_data: CollectProtocolData,
    pub tx_information: TxInformation,
}

pub type FlashData = rindexer_uniswap_v3_pool_filter_gen::FlashFilter;

#[derive(Debug, Clone)]
pub struct FlashResult {
    pub event_data: FlashData,
    pub tx_information: TxInformation,
}

pub type IncreaseObservationCardinalityNextData =
    rindexer_uniswap_v3_pool_filter_gen::IncreaseObservationCardinalityNextFilter;

#[derive(Debug, Clone)]
pub struct IncreaseObservationCardinalityNextResult {
    pub event_data: IncreaseObservationCardinalityNextData,
    pub tx_information: TxInformation,
}

pub type InitializeData = rindexer_uniswap_v3_pool_filter_gen::InitializeFilter;

#[derive(Debug, Clone)]
pub struct InitializeResult {
    pub event_data: InitializeData,
    pub tx_information: TxInformation,
}

pub type MintData = rindexer_uniswap_v3_pool_filter_gen::MintFilter;

#[derive(Debug, Clone)]
pub struct MintResult {
    pub event_data: MintData,
    pub tx_information: TxInformation,
}

pub type SetFeeProtocolData = rindexer_uniswap_v3_pool_filter_gen::SetFeeProtocolFilter;

#[derive(Debug, Clone)]
pub struct SetFeeProtocolResult {
    pub event_data: SetFeeProtocolData,
    pub tx_information: TxInformation,
}

pub type SwapData = rindexer_uniswap_v3_pool_filter_gen::SwapFilter;

#[derive(Debug, Clone)]
pub struct SwapResult {
    pub event_data: SwapData,
    pub tx_information: TxInformation,
}

type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

#[async_trait]
trait EventCallback {
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()>;
}

pub struct EventContext<TExtensions>
where
    TExtensions: Send + Sync,
{
    pub database: Arc<PostgresClient>,
    pub csv: Arc<AsyncCsvAppender>,
    pub extensions: Arc<TExtensions>,
}

// didn't want to use option or none made harder DX
// so a blank struct makes interface nice
pub struct NoExtensions {}
pub fn no_extensions() -> NoExtensions {
    NoExtensions {}
}

pub fn swap_handler<TExtensions, F, Fut>(custom_logic: F) -> SwapEventCallbackType<TExtensions>
where
    SwapResult: Clone + 'static,
    F: for<'a> Fn(Vec<SwapResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type SwapEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<SwapResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct SwapEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: SwapEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> SwapEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        SwapResult: Clone + 'static,
        F: for<'a> Fn(Vec<SwapResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        let csv = AsyncCsvAppender::new("/Users/joshstevens/code/rindexer/rindexer_rust_playground/./generated_csv/UniswapV3PoolFilter/uniswapv3poolfilter-swap.csv");
        if !Path::new("/Users/joshstevens/code/rindexer/rindexer_rust_playground/./generated_csv/UniswapV3PoolFilter/uniswapv3poolfilter-swap.csv").exists() {
            csv.append_header(vec!["contract_address".into(), "sender".into(), "recipient".into(), "amount_0".into(), "amount_1".into(), "sqrt_price_x96".into(), "liquidity".into(), "tick".into(), "tx_hash".into(), "block_number".into(), "block_hash".into(), "network".into(), "tx_index".into(), "log_index".into()])
                .await
                .expect("Failed to write CSV header");
        }

        Self {
            callback: swap_handler(closure),
            context: Arc::new(EventContext {
                database: get_or_init_postgres_client().await,
                csv: Arc::new(csv),
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for SwapEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<SwapResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data.downcast::<SwapData>().ok().map(|arc| SwapResult {
                    event_data: (*arc).clone(),
                    tx_information: item.tx_information,
                })
            })
            .collect();

        (self.callback)(&result, Arc::clone(&self.context)).await
    }
}

pub enum UniswapV3PoolFilterEventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    Swap(SwapEvent<TExtensions>),
}

pub fn uniswap_v3_pool_filter_contract(
    network: &str,
    address: Address,
) -> RindexerUniswapV3PoolFilterGen<Arc<Provider<RetryClient<Http>>>> {
    RindexerUniswapV3PoolFilterGen::new(
        address,
        Arc::new(get_provider_cache_for_network(network).get_inner_provider()),
    )
}

pub fn decoder_contract(
    network: &str,
) -> RindexerUniswapV3PoolFilterGen<Arc<Provider<RetryClient<Http>>>> {
    if network == "base" {
        RindexerUniswapV3PoolFilterGen::new(
            // do not care about address here its decoding makes it easier to handle ValueOrArray
            Address::zero(),
            Arc::new(get_provider_cache_for_network(network).get_inner_provider()),
        )
    } else {
        panic!("Network not supported");
    }
}

impl<TExtensions> UniswapV3PoolFilterEventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    pub fn topic_id(&self) -> &'static str {
        match self {
            UniswapV3PoolFilterEventType::Swap(_) => {
                "0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"
            }
        }
    }

    pub fn event_name(&self) -> &'static str {
        match self {
            UniswapV3PoolFilterEventType::Swap(_) => "Swap",
        }
    }

    pub fn contract_name(&self) -> String {
        "UniswapV3Pool".to_string()
    }

    fn get_provider(&self, network: &str) -> Arc<JsonRpcCachedProvider> {
        get_provider_cache_for_network(network)
    }

    fn decoder(
        &self,
        network: &str,
    ) -> Arc<dyn Fn(Vec<H256>, Bytes) -> Arc<dyn Any + Send + Sync> + Send + Sync> {
        let decoder_contract = decoder_contract(network);

        match self {
            UniswapV3PoolFilterEventType::Swap(_) => {
                Arc::new(move |topics: Vec<H256>, data: Bytes| {
                    match decoder_contract.decode_event::<SwapData>("Swap", topics, data) {
                        Ok(filter) => Arc::new(filter) as Arc<dyn Any + Send + Sync>,
                        Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                    }
                })
            }
        }
    }

    pub fn register(self, manifest_path: &PathBuf, registry: &mut EventCallbackRegistry) {
        let rindexer_yaml = read_manifest(manifest_path).expect("Failed to read rindexer.yaml");
        let topic_id = self.topic_id();
        let contract_name = self.contract_name();
        let event_name = self.event_name();

        let contract_details = rindexer_yaml
            .contracts
            .iter()
            .find(|c| c.name == contract_name)
            .unwrap_or_else(|| {
                panic!(
                    "Contract {} not found please make sure its defined in the rindexer.yaml",
                    contract_name
                )
            })
            .clone();

        let index_event_in_order = contract_details
            .index_event_in_order
            .as_ref()
            .map_or(false, |vec| vec.contains(&event_name.to_string()));

        let contract = ContractInformation {
            name: contract_details.before_modify_name_if_filter_readonly().into_owned(),
            details: contract_details
                .details
                .iter()
                .map(|c| NetworkContract {
                    id: generate_random_id(10),
                    network: c.network.clone(),
                    cached_provider: self.get_provider(&c.network),
                    decoder: self.decoder(&c.network),
                    indexing_contract_setup: c.indexing_contract_setup(),
                    start_block: c.start_block,
                    end_block: c.end_block,
                    disable_logs_bloom_checks: rindexer_yaml
                        .networks
                        .iter()
                        .find(|n| n.name == c.network)
                        .map_or(false, |n| n.disable_logs_bloom_checks.unwrap_or_default()),
                })
                .collect(),
            abi: contract_details.abi,
            reorg_safe_distance: contract_details.reorg_safe_distance.unwrap_or_default(),
        };

        let callback: Arc<
            dyn Fn(Vec<EventResult>) -> BoxFuture<'static, EventCallbackResult<()>> + Send + Sync,
        > = match self {
            UniswapV3PoolFilterEventType::Swap(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }
        };

        registry.register_event(EventCallbackRegistryInformation {
            id: generate_random_id(10),
            indexer_name: "RindexerPlayground".to_string(),
            event_name: event_name.to_string(),
            index_event_in_order,
            topic_id: topic_id.parse::<H256>().unwrap(),
            contract,
            callback,
        });
    }
}
