apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rindexer.fullname" . }}-abis
  labels:
    {{- include "rindexer.labels" . | nindent 4 }}
data:
  RocketTokenRETH.abi.json: |
    {{ .Files.Get "files/abis/RocketTokenRETH.abi.json" | indent 4 }}
