services:
  redis:
    image: redis
    container_name: rindexer-redis
    logging:
      driver: none
    ports:
      - "6379:6379"
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
