#![allow(
    non_camel_case_types,
    clippy::enum_variant_names,
    clippy::too_many_arguments,
    clippy::upper_case_acronyms,
    clippy::type_complexity,
    dead_code
)]
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
        ///
        /// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
        /// Any manual changes to this file will be overwritten.

        use super::uniswap_v3_factory_pool_created_token_0_token_1_abi_gen::{
            RindexerUniswapV3FactoryPoolCreatedToken0Token1Gen::{self, RindexerUniswapV3FactoryPoolCreatedToken0Token1GenInstance, RindexerUniswapV3FactoryPoolCreatedToken0Token1GenEvents}
        };
        use std::{any::Any, sync::Arc};
        use std::error::Error;
        use std::future::Future;
        use std::collections::HashMap;
        use std::pin::Pin;
        use std::path::{Path, PathBuf};
        use alloy::network::AnyNetwork;
        use alloy::primitives::{Address, Bytes, B256};
        use alloy::sol_types::{SolEvent, SolEventInterface, SolType};
        use rindexer::{
            async_trait,
            AsyncCsvAppender,
            generate_random_id,
            FutureExt,
            blockclock::BlockClock,
            event::{
                callback_registry::{
                    EventCallbackRegistry, EventCallbackRegistryInformation, EventCallbackResult,
                    EventResult, TxInformation, HasTxInformation
                },
                contract_setup::{ContractInformation, NetworkContract},
            },
            manifest::{
                contract::{Contract, ContractDetails},
                yaml::read_manifest,
            },
            provider::{JsonRpcCachedProvider, RindexerProvider},
            PostgresClient,
        };
        use super::super::super::super::typings::networks::get_provider_cache_for_network;
        use super::super::super::super::typings::database::get_or_init_postgres_client;

pub type FeeAmountEnabledData =
    RindexerUniswapV3FactoryPoolCreatedToken0Token1Gen::FeeAmountEnabled;

#[derive(Debug, Clone)]
pub struct FeeAmountEnabledResult {
    pub event_data: FeeAmountEnabledData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for FeeAmountEnabledResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type OwnerChangedData = RindexerUniswapV3FactoryPoolCreatedToken0Token1Gen::OwnerChanged;

#[derive(Debug, Clone)]
pub struct OwnerChangedResult {
    pub event_data: OwnerChangedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for OwnerChangedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type PoolCreatedData = RindexerUniswapV3FactoryPoolCreatedToken0Token1Gen::PoolCreated;

#[derive(Debug, Clone)]
pub struct PoolCreatedResult {
    pub event_data: PoolCreatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for PoolCreatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

#[async_trait]
trait EventCallback {
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()>;
}

pub struct EventContext<TExtensions>
where
    TExtensions: Send + Sync,
{
    pub database: Arc<PostgresClient>,
    pub csv: Arc<AsyncCsvAppender>,
    pub extensions: Arc<TExtensions>,
}

// didn't want to use option or none made harder DX
// so a blank struct makes interface nice
pub struct NoExtensions {}
pub fn no_extensions() -> NoExtensions {
    NoExtensions {}
}

pub fn poolcreated_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> PoolCreatedEventCallbackType<TExtensions>
where
    PoolCreatedResult: Clone + 'static,
    F: for<'a> Fn(Vec<PoolCreatedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type PoolCreatedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<PoolCreatedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct PoolCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: PoolCreatedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> PoolCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        PoolCreatedResult: Clone + 'static,
        F: for<'a> Fn(Vec<PoolCreatedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        let csv_path = std::env::current_dir().expect("Failed to get current directory").join(r"generated_csv/UniswapV3FactoryPoolCreatedToken0Token1/uniswapv3factorypoolcreatedtoken0token1-poolcreated.csv");
        let csv = AsyncCsvAppender::new(csv_path.to_str().expect("Failed to convert csv path"));
        if !csv_path.exists() {
            csv.append_header(
                vec![
                    "contract_address".into(),
                    "token_0".into(),
                    "token_1".into(),
                    "fee".into(),
                    "tick_spacing".into(),
                    "pool".into(),
                    "tx_hash".into(),
                    "block_number".into(),
                    "block_hash".into(),
                    "network".into(),
                    "tx_index".into(),
                    "log_index".into(),
                ]
                .into(),
            )
            .await
            .expect("Failed to write CSV header");
        }

        Self {
            callback: poolcreated_handler(closure),
            context: Arc::new(EventContext {
                database: get_or_init_postgres_client().await,
                csv: Arc::new(csv),
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for PoolCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<PoolCreatedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data.downcast::<PoolCreatedData>().ok().map(|arc| PoolCreatedResult {
                    event_data: (*arc).clone(),
                    tx_information: item.tx_information,
                })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!("PoolCreatedEvent: Unexpected data type - expected: PoolCreatedData")
        }
    }
}

pub enum UniswapV3FactoryPoolCreatedToken0Token1EventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    PoolCreated(PoolCreatedEvent<TExtensions>),
}

pub async fn uniswap_v3_factory_pool_created_token_0_token_1_contract(
    network: &str,
    address: Address,
) -> RindexerUniswapV3FactoryPoolCreatedToken0Token1GenInstance<Arc<RindexerProvider>, AnyNetwork> {
    RindexerUniswapV3FactoryPoolCreatedToken0Token1Gen::new(
        address,
        get_provider_cache_for_network(network).await.get_inner_provider(),
    )
}

pub async fn decoder_contract(
    network: &str,
) -> RindexerUniswapV3FactoryPoolCreatedToken0Token1GenInstance<Arc<RindexerProvider>, AnyNetwork> {
    if network == "base" {
        RindexerUniswapV3FactoryPoolCreatedToken0Token1Gen::new(
            // do not care about address here its decoding makes it easier to handle ValueOrArray
            Address::ZERO,
            get_provider_cache_for_network(network).await.get_inner_provider(),
        )
    } else if network == "ethereum" {
        RindexerUniswapV3FactoryPoolCreatedToken0Token1Gen::new(
            // do not care about address here its decoding makes it easier to handle ValueOrArray
            Address::ZERO,
            get_provider_cache_for_network(network).await.get_inner_provider(),
        )
    } else {
        panic!("Network not supported");
    }
}

impl<TExtensions> UniswapV3FactoryPoolCreatedToken0Token1EventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    pub fn topic_id(&self) -> &'static str {
        match self {
            UniswapV3FactoryPoolCreatedToken0Token1EventType::PoolCreated(_) => {
                "0x783cca1c0412dd0d695e784568c96da2e9c22ff989357a2e8b1d9b2b4e6b7118"
            }
        }
    }

    pub fn event_name(&self) -> &'static str {
        match self {
            UniswapV3FactoryPoolCreatedToken0Token1EventType::PoolCreated(_) => "PoolCreated",
        }
    }

    pub fn contract_name(&self) -> String {
        "UniswapV3FactoryPoolCreatedToken0Token1".to_string()
    }

    async fn get_provider(&self, network: &str) -> Arc<JsonRpcCachedProvider> {
        get_provider_cache_for_network(network).await
    }

    fn decoder(
        &self,
        network: &str,
    ) -> Arc<dyn Fn(Vec<B256>, Bytes) -> Arc<dyn Any + Send + Sync> + Send + Sync> {
        let decoder_contract = decoder_contract(network);

        match self {
            UniswapV3FactoryPoolCreatedToken0Token1EventType::PoolCreated(_) => Arc::new(
                move |topics: Vec<B256>, data: Bytes| match PoolCreatedData::decode_raw_log(
                    topics,
                    &data[0..],
                ) {
                    Ok(event) => {
                        let result: PoolCreatedData = event;
                        Arc::new(result) as Arc<dyn Any + Send + Sync>
                    }
                    Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                },
            ),
        }
    }

    pub async fn register(self, manifest_path: &PathBuf, registry: &mut EventCallbackRegistry) {
        let rindexer_yaml = read_manifest(manifest_path).expect("Failed to read rindexer.yaml");
        let topic_id = self.topic_id();
        let contract_name = self.contract_name();
        let event_name = self.event_name();

        let contract_details = rindexer_yaml
            .all_contracts()
            .iter()
            .find(|c| c.name == contract_name)
            .unwrap_or_else(|| {
                panic!(
                    "Contract {} not found please make sure its defined in the rindexer.yaml",
                    contract_name
                )
            })
            .clone();

        let index_event_in_order = contract_details
            .index_event_in_order
            .as_ref()
            .map_or(false, |vec| vec.contains(&event_name.to_string()));

        // Expect providers to have been initialized, but it's an async init so this should
        // be fast but for correctness we must await each future.
        let mut providers = HashMap::new();
        for n in contract_details.details.iter() {
            let provider = self.get_provider(&n.network).await;
            providers.insert(n.network.clone(), provider);
        }

        let contract = ContractInformation {
            name: contract_details.before_modify_name_if_filter_readonly().into_owned(),
            details: contract_details
                .details
                .iter()
                .map(|c| {
                    let provider = providers.get(&c.network).expect("must have a provider").clone();

                    NetworkContract {
                        id: generate_random_id(10),
                        network: c.network.clone(),
                        cached_provider: provider.clone(),
                        block_clock: BlockClock::new(
                            rindexer_yaml.timestamps,
                            rindexer_yaml.config.timestamp_sample_rate,
                            provider.clone(),
                        ),
                        decoder: self.decoder(&c.network),
                        indexing_contract_setup: c.indexing_contract_setup(manifest_path),
                        start_block: c.start_block,
                        end_block: c.end_block,
                        disable_logs_bloom_checks: rindexer_yaml
                            .networks
                            .iter()
                            .find(|n| n.name == c.network)
                            .map_or(false, |n| n.disable_logs_bloom_checks.unwrap_or_default()),
                    }
                })
                .collect(),
            abi: contract_details.abi,
            reorg_safe_distance: contract_details.reorg_safe_distance.unwrap_or_default(),
        };

        let callback: Arc<
            dyn Fn(Vec<EventResult>) -> BoxFuture<'static, EventCallbackResult<()>> + Send + Sync,
        > = match self {
            UniswapV3FactoryPoolCreatedToken0Token1EventType::PoolCreated(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }
        };

        registry.register_event(EventCallbackRegistryInformation {
            id: generate_random_id(10),
            indexer_name: "RindexerFactoryContract".to_string(),
            event_name: event_name.to_string(),
            index_event_in_order,
            topic_id: topic_id.parse::<B256>().unwrap(),
            contract,
            callback,
        });
    }
}
