new:
	cargo run -- new
generate:
	cargo run -- generate
ls_networks:
	cargo run -- ls networks
ls_indexers:
	cargo run -- ls indexers
ls_global:
	cargo run -- ls global
network_add:
	cargo run -- network-add
network_delete:
	cargo run -- network-delete