new:
	cargo run -- new
start:
	cargo run -- start all
start_indexer:
	cargo run -- start indexer
dev:
	cargo run -- dev
codegen:
	cargo run -- codegen all
codegen_typings:
	cargo run -- codegen typings
codegen_indexer:
	cargo run -- codegen indexer
download_abi:
	cargo run -- download_abi